version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      
  build:
    commands:
      - echo "Fase de Build ejecutando script..."
      - python procesar.py
      - bash -c "if [ -f resultado.txt ]; then echo 'Exito, resultado.txt existe'; else echo 'Error' && exit 1; fi"
      
  post_build:
    commands:
      - echo "Subiendo a S3..."
      - aws s3 cp index.html s3://$S3_BUCKET/
      - aws s3 cp css/ s3://$S3_BUCKET/css/ --recursive
      - aws s3 cp js/ s3://$S3_BUCKET/js/ --recursive
      - aws s3 cp resultado.txt s3://$S3_BUCKET/
      - echo "Configurando llave SSH..."
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo "Desplegando en EC2..."
      - scp -o StrictHostKeyChecking=no -r ./* ubuntu@$52.14.218.34:/home/ubuntu/
      - ssh -o StrictHostKeyChecking=no ubuntu@$52.14.218.34 "sudo apt-get update && sudo apt-get install -y docker.io && sudo docker build -t app-actividad4 /home/ubuntu/ && sudo docker stop mi-app || true && sudo docker rm mi-app || true && sudo docker run -d -p 80:80 --name mi-app app-actividad4"