version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      
  build:
    commands:
      - echo "Fase de Build iniciada..."
      
  post_build:
    commands:
      - echo "Subiendo archivos web al bucket S3..."
      - aws s3 cp index.html s3://$S3_BUCKET/
      - aws s3 cp css/ s3://$S3_BUCKET/css/ --recursive
      - aws s3 cp js/ s3://$S3_BUCKET/js/ --recursive
      
      - echo "Configurando llave SSH..."
      - mkdir -p ~/.ssh
      # OJO: Asegúrate de que el nombre del .pem coincida con el que subiste a S3
      - aws s3 cp s3://$S3_BUCKET/Extractor.pem ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      
      - echo "Desplegando archivos en EC2..."
      - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./* ubuntu@3.139.58.49:/home/ubuntu/
      
      - echo "Ejecutando script y Docker en la instancia EC2..."
      # Entramos a la EC2, ejecutamos el script de Python, y levantamos Docker
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@3.139.58.49 "cd /home/ubuntu/ && python3 procesar.py && sudo apt-get update && sudo apt-get install -y docker.io && sudo docker build -t app-actividad4 . && sudo docker stop mi-app || true && sudo docker rm mi-app || true && sudo docker run -d -p 80:80 --name mi-app app-actividad4"